import React from 'react'

const About = () => {
  return (
    <div name='about' className='w-full h-screen bg-gradient-to-b from-black via-black to-gray-800 text-white py-8'>
      <div className='max-w-screen-lg p-4 mx-auto flex flex-col justify-center w-full h-full'>
        <div className='pb-8'>
          <p className='text-4xl font-b inline border-b-4 border-gray-400'>About</p>
        </div>
        <p className='text-xl mt-20'>
          With the will of fire that burns brighter,with the hunger to know more, i entered in the era of tech.
          And immediately i saw an another world that was growing i.e the world of tech. 
          I always have had an intution to build something, design something and later i decided to listen to my
          inner voice and started my journey in development and designing.
        </p>
        <br />
        <p className='text-xl'>
          A piece of code that can define something,that can defy the normal understanding. Its soo
          cool to see how few lines of code do some magic. I was always fond of coding. Being an engineering student its final year and i got to
          know alot regarding the digital world and how it runs. I have always improved the mistakes and learned it as it is a life lesson.
          If you want to make something that is generated by the magic of codes i m the guy you are looking for!!
        </p>
      </div>
    </div>
  )
}

export default About;